filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
tools:
    external_code_coverage: true
    php_cpd: true
    php_pdepend: true
    php_mess_detector:
        config:
            ruleset: phpmd_rules.xml
    php_loc: true
