language: php
php:
  - 5.5
  - 5.4
services: mysql

before_script:
  - sh -c "sudo apt-get install uuid-dev"
  - curl -L -o libevent-1.4.14b-stable.tar.gz https://github.com/downloads/libevent/libevent/libevent-1.4.14b-stable.tar.gz
  - tar -xzf libevent-1.4.14b-stable.tar.gz
  - sh -c "cd libevent-1.4.14b-stable && ./configure && make && sudo make install && cd .. && rm -rf libevent-1.4.14b-stable"
  - curl -L -o gearmand-0.14.tar.gz https://launchpad.net/gearmand/1.0/0.14/+download/gearmand-0.14.tar.gz
  - tar -xzf gearmand-0.14.tar.gz
  - sh -c "cd gearmand-0.14 && ./configure && make && sudo make install && cd .. && rm -rf gearmand-0.14"
  - curl -L -o gearman-0.8.3.tgz http://pecl.php.net/get/gearman/0.8.3
  - tar -xzf gearman-0.8.3.tgz
  - sh -c "cd gearman-0.8.3 && phpize && ./configure && make && sudo make install && cd .. && rm -rf gearman-0.8.3"
  - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: make fullbuild
