language: php

php:
  - 5.6

sudo: false

services: mysql

cache:
    directories:
        - $HOME/.composer/cache

before_install: composer self-update

install: composer install --prefer-dist

script: make fullbuild
